/**
 * Make/model catalogue tuned for what is actually sold on the Czech and Slovak used-car market.
 * Aliases are matched against folded text (lowercase, no diacritics) on word boundaries.
 * `patterns` catch model codes such as BMW "320d" or Mercedes "C220" that never spell the model name.
 */
export type ModelDef = {
  slug: string;
  name: string;
  aliases?: string[];
  patterns?: RegExp[];
  body?: string;
};

export type MakeDef = {
  slug: string;
  name: string;
  aliases: string[];
  models: ModelDef[];
};

const m = (slug: string, name: string, aliases: string[] = [], body?: string, patterns?: RegExp[]): ModelDef => ({
  slug,
  name,
  aliases,
  body,
  patterns,
});

export const CATALOG: MakeDef[] = [
  {
    slug: "skoda",
    name: "Škoda",
    aliases: ["skoda", "skodovka"],
    models: [
      m("octavia", "Octavia", ["octavia", "oktavia", "octavie", "octavka", "oktavka"]),
      m("fabia", "Fabia", ["fabia", "fabie", "fabka"], "hatchback"),
      m("superb", "Superb", ["superb", "superbe"]),
      m("rapid", "Rapid", ["rapid", "spaceback"]),
      m("kodiaq", "Kodiaq", ["kodiaq", "kodiak"], "suv"),
      m("karoq", "Karoq", ["karoq", "karok"], "suv"),
      m("kamiq", "Kamiq", ["kamiq", "kamik"], "suv"),
      m("scala", "Scala", ["scala"], "hatchback"),
      m("yeti", "Yeti", ["yeti"], "suv"),
      m("roomster", "Roomster", ["roomster"], "mpv"),
      m("citigo", "Citigo", ["citigo"], "hatchback"),
      m("enyaq", "Enyaq", ["enyaq"], "suv"),
      m("elroq", "Elroq", ["elroq"], "suv"),
      m("felicia", "Felicia", ["felicia", "felicie"]),
      m("favorit", "Favorit", ["favorit", "forman"]),
      m("120", "105/120/130", ["120", "105", "130", "136", "rapid 130"]),
    ],
  },
  {
    slug: "volkswagen",
    name: "Volkswagen",
    aliases: ["volkswagen", "vw", "volkswagon", "folksvagen"],
    models: [
      m("golf", "Golf", ["golf", "golf plus", "golf sportsvan"]),
      m("passat", "Passat", ["passat", "pasat"]),
      m("polo", "Polo", ["polo"], "hatchback"),
      m("tiguan", "Tiguan", ["tiguan"], "suv"),
      m("touran", "Touran", ["touran"], "mpv"),
      m("touareg", "Touareg", ["touareg", "tuareg"], "suv"),
      m("sharan", "Sharan", ["sharan"], "mpv"),
      m("caddy", "Caddy", ["caddy"], "van"),
      m("transporter", "Transporter", ["transporter", "multivan", "caravelle", "t4", "t5", "t6", "t6.1"], "van"),
      m("t-roc", "T-Roc", ["t-roc", "troc", "t roc"], "suv"),
      m("t-cross", "T-Cross", ["t-cross", "tcross", "t cross"], "suv"),
      m("arteon", "Arteon", ["arteon"]),
      m("jetta", "Jetta", ["jetta"], "sedan"),
      m("bora", "Bora", ["bora"], "sedan"),
      m("up", "up!", ["up!", "up"], "hatchback"),
      m("scirocco", "Scirocco", ["scirocco"], "coupe"),
      m("amarok", "Amarok", ["amarok"], "pickup"),
      m("id3", "ID.3", ["id.3", "id3", "id 3"], "hatchback"),
      m("id4", "ID.4", ["id.4", "id4", "id 4"], "suv"),
      m("crafter", "Crafter", ["crafter"], "van"),
      m("fox", "Fox", ["fox"], "hatchback"),
      m("beetle", "Beetle", ["beetle", "brouk", "chrobak"]),
    ],
  },
  {
    slug: "audi",
    name: "Audi",
    aliases: ["audi"],
    models: [
      m("a1", "A1", ["a1"]),
      m("a3", "A3", ["a3", "s3", "rs3"]),
      m("a4", "A4", ["a4", "s4", "rs4", "a4 allroad"]),
      m("a5", "A5", ["a5", "s5", "rs5"]),
      m("a6", "A6", ["a6", "s6", "rs6", "a6 allroad"]),
      m("a7", "A7", ["a7", "s7", "rs7"]),
      m("a8", "A8", ["a8", "s8"]),
      m("q2", "Q2", ["q2"], "suv"),
      m("q3", "Q3", ["q3"], "suv"),
      m("q5", "Q5", ["q5", "sq5"], "suv"),
      m("q7", "Q7", ["q7", "sq7"], "suv"),
      m("q8", "Q8", ["q8", "sq8"], "suv"),
      m("tt", "TT", ["tt", "tts"], "coupe"),
      m("e-tron", "e-tron", ["e-tron", "etron", "q4 e-tron", "q4"], "suv"),
      m("80", "80/100", ["80", "100", "a80"]),
    ],
  },
  {
    slug: "bmw",
    name: "BMW",
    aliases: ["bmw", "bavorak"],
    models: [
      m("1-series", "Řada 1", ["rada 1", "1 series", "seria 1", "1er"], "hatchback", [/\b1[1-4]\d ?[id]\b/, /\bm1[34]5i\b/]),
      m("2-series", "Řada 2", ["rada 2", "2 series", "seria 2", "2er", "active tourer", "gran tourer"], undefined, [/\b2[1-4]\d ?[id]\b/, /\bm2\b/]),
      m("3-series", "Řada 3", ["rada 3", "3 series", "seria 3", "3er", "e46", "e90", "e91", "f30", "f31", "g20", "g21"], undefined, [/\b3[1-4]\d ?(?:[id]|xd|xi|e)\b/, /\bm3\b/]),
      m("4-series", "Řada 4", ["rada 4", "4 series", "seria 4", "4er", "gran coupe"], "coupe", [/\b4[1-4]\d ?(?:[id]|xd|xi)\b/, /\bm4\b/]),
      m("5-series", "Řada 5", ["rada 5", "5 series", "seria 5", "5er", "e39", "e60", "e61", "f10", "f11", "g30", "g31"], undefined, [/\b5[1-5]\d ?(?:[id]|xd|xi|e)\b/, /\bm5\b/]),
      m("6-series", "Řada 6", ["rada 6", "6 series", "6er"], undefined, [/\b6[2-5]\d ?(?:[id]|xd|xi)\b/]),
      m("7-series", "Řada 7", ["rada 7", "7 series", "7er"], "sedan", [/\b7[2-6]\d ?(?:[id]|li|xd|ld)\b/]),
      m("x1", "X1", ["x1"], "suv"),
      m("x2", "X2", ["x2"], "suv"),
      m("x3", "X3", ["x3"], "suv"),
      m("x4", "X4", ["x4"], "suv"),
      m("x5", "X5", ["x5", "e70", "f15", "g05"], "suv"),
      m("x6", "X6", ["x6"], "suv"),
      m("x7", "X7", ["x7"], "suv"),
      m("i3", "i3", ["i3"], "hatchback"),
      m("z4", "Z4", ["z4"], "cabrio"),
    ],
  },
  {
    slug: "mercedes-benz",
    name: "Mercedes-Benz",
    aliases: ["mercedes-benz", "mercedes benz", "mercedes", "mb", "merc", "mercedez"],
    models: [
      m("a-class", "Třída A", ["trida a", "a-class", "a trieda", "a-klasse"], "hatchback", [/\ba ?1[5-9]0\b/, /\ba ?2[0-5]0\b/, /\ba ?35 amg\b/]),
      m("b-class", "Třída B", ["trida b", "b-class", "b trieda"], "mpv", [/\bb ?1[5-9]0\b/, /\bb ?2[0-5]0\b/]),
      m("c-class", "Třída C", ["trida c", "c-class", "c trieda", "c-klasse", "w203", "w204", "w205", "w206", "s204", "s205"], undefined, [/\bc ?(?:180|200|220|230|250|270|280|300|320|350|400|43|63)\b/]),
      m("e-class", "Třída E", ["trida e", "e-class", "e trieda", "e-klasse", "w210", "w211", "w212", "w213", "s211", "s212", "s213"], undefined, [/\be ?(?:200|220|250|270|280|300|320|350|400|420|450|500|43|63)\b/]),
      m("s-class", "Třída S", ["trida s", "s-class", "s trieda", "w221", "w222", "w223"], "sedan", [/\bs ?(?:320|350|400|450|500|550|560|580|600|63|65)\b/]),
      m("cla", "CLA", ["cla"], "coupe"),
      m("cls", "CLS", ["cls"], "coupe"),
      m("gla", "GLA", ["gla"], "suv"),
      m("glb", "GLB", ["glb"], "suv"),
      m("glc", "GLC", ["glc"], "suv"),
      m("gle", "GLE", ["gle", "ml"], "suv", [/\bml ?(?:250|270|280|320|350|400|420|500)\b/]),
      m("gls", "GLS", ["gls", "gl"], "suv"),
      m("g-class", "Třída G", ["trida g", "g-class", "g trieda"], "suv"),
      m("vito", "Vito", ["vito", "viano", "v-class", "trida v"], "van"),
      m("sprinter", "Sprinter", ["sprinter"], "van"),
      m("citan", "Citan", ["citan"], "van"),
    ],
  },
  {
    slug: "ford",
    name: "Ford",
    aliases: ["ford"],
    models: [
      m("focus", "Focus", ["focus", "fokus", "c-max", "cmax"]),
      m("fiesta", "Fiesta", ["fiesta"], "hatchback"),
      m("mondeo", "Mondeo", ["mondeo"]),
      m("kuga", "Kuga", ["kuga"], "suv"),
      m("s-max", "S-Max", ["s-max", "smax", "galaxy"], "mpv"),
      m("transit", "Transit", ["transit", "tourneo"], "van"),
      m("puma", "Puma", ["puma"], "suv"),
      m("ecosport", "EcoSport", ["ecosport", "eco sport"], "suv"),
      m("ka", "Ka", ["ka", "ka+"], "hatchback"),
      m("mustang", "Mustang", ["mustang"], "coupe"),
      m("ranger", "Ranger", ["ranger"], "pickup"),
    ],
  },
  {
    slug: "opel",
    name: "Opel",
    aliases: ["opel"],
    models: [
      m("astra", "Astra", ["astra"]),
      m("corsa", "Corsa", ["corsa"], "hatchback"),
      m("insignia", "Insignia", ["insignia"]),
      m("vectra", "Vectra", ["vectra"]),
      m("zafira", "Zafira", ["zafira"], "mpv"),
      m("meriva", "Meriva", ["meriva"], "mpv"),
      m("mokka", "Mokka", ["mokka"], "suv"),
      m("grandland", "Grandland", ["grandland"], "suv"),
      m("crossland", "Crossland", ["crossland"], "suv"),
      m("vivaro", "Vivaro", ["vivaro"], "van"),
      m("combo", "Combo", ["combo"], "van"),
      m("agila", "Agila", ["agila"], "hatchback"),
      m("omega", "Omega", ["omega"]),
    ],
  },
  {
    slug: "renault",
    name: "Renault",
    aliases: ["renault", "reno"],
    models: [
      m("megane", "Mégane", ["megane", "megan", "scenic", "grand scenic"]),
      m("clio", "Clio", ["clio"], "hatchback"),
      m("captur", "Captur", ["captur"], "suv"),
      m("kadjar", "Kadjar", ["kadjar"], "suv"),
      m("laguna", "Laguna", ["laguna"]),
      m("talisman", "Talisman", ["talisman"]),
      m("thalia", "Thalia", ["thalia"], "sedan"),
      m("kangoo", "Kangoo", ["kangoo"], "van"),
      m("trafic", "Trafic", ["trafic", "traffic"], "van"),
      m("master", "Master", ["master"], "van"),
      m("zoe", "Zoe", ["zoe"], "hatchback"),
      m("espace", "Espace", ["espace"], "mpv"),
      m("koleos", "Koleos", ["koleos"], "suv"),
      m("twingo", "Twingo", ["twingo"], "hatchback"),
      m("austral", "Austral", ["austral"], "suv"),
      m("arkana", "Arkana", ["arkana"], "suv"),
    ],
  },
  {
    slug: "dacia",
    name: "Dacia",
    aliases: ["dacia", "dacie"],
    models: [
      m("duster", "Duster", ["duster"], "suv"),
      m("sandero", "Sandero", ["sandero", "stepway"], "hatchback"),
      m("logan", "Logan", ["logan", "mcv"]),
      m("lodgy", "Lodgy", ["lodgy"], "mpv"),
      m("dokker", "Dokker", ["dokker"], "van"),
      m("jogger", "Jogger", ["jogger"], "mpv"),
      m("spring", "Spring", ["spring"], "hatchback"),
      m("bigster", "Bigster", ["bigster"], "suv"),
    ],
  },
  {
    slug: "peugeot",
    name: "Peugeot",
    aliases: ["peugeot", "pezo", "pezot"],
    models: [
      m("206", "206", ["206"]),
      m("207", "207", ["207"]),
      m("208", "208", ["208"], "hatchback"),
      m("307", "307", ["307"]),
      m("308", "308", ["308"]),
      m("407", "407", ["407"]),
      m("508", "508", ["508"]),
      m("2008", "2008", ["2008"], "suv"),
      m("3008", "3008", ["3008"], "suv"),
      m("5008", "5008", ["5008"], "suv"),
      m("partner", "Partner", ["partner", "rifter"], "van"),
      m("boxer", "Boxer", ["boxer"], "van"),
      m("expert", "Expert", ["expert", "traveller"], "van"),
      m("107", "107/108", ["107", "108"], "hatchback"),
    ],
  },
  {
    slug: "citroen",
    name: "Citroën",
    aliases: ["citroen", "citroen", "citron"],
    models: [
      m("c3", "C3", ["c3", "c3 aircross", "c3 picasso"]),
      m("c4", "C4", ["c4", "c4 picasso", "grand c4", "c4 cactus", "c4 spacetourer"]),
      m("c5", "C5", ["c5", "c5 aircross", "c5 x"]),
      m("c1", "C1", ["c1"], "hatchback"),
      m("berlingo", "Berlingo", ["berlingo"], "van"),
      m("jumper", "Jumper", ["jumper"], "van"),
      m("jumpy", "Jumpy", ["jumpy", "spacetourer"], "van"),
      m("xsara", "Xsara", ["xsara", "xsara picasso"]),
      m("ds", "DS", ["ds3", "ds4", "ds5"]),
    ],
  },
  {
    slug: "hyundai",
    name: "Hyundai",
    aliases: ["hyundai", "hyunday", "hundai"],
    models: [
      m("i10", "i10", ["i10"], "hatchback"),
      m("i20", "i20", ["i20"], "hatchback"),
      m("i30", "i30", ["i30"]),
      m("i40", "i40", ["i40"]),
      m("ix20", "ix20", ["ix20"], "mpv"),
      m("ix35", "ix35", ["ix35"], "suv"),
      m("tucson", "Tucson", ["tucson"], "suv"),
      m("santa-fe", "Santa Fe", ["santa fe", "santafe"], "suv"),
      m("kona", "Kona", ["kona"], "suv"),
      m("bayon", "Bayon", ["bayon"], "suv"),
      m("ioniq", "Ioniq", ["ioniq", "ioniq 5", "ioniq 6"]),
      m("getz", "Getz", ["getz"], "hatchback"),
    ],
  },
  {
    slug: "kia",
    name: "Kia",
    aliases: ["kia"],
    models: [
      m("ceed", "Ceed", ["ceed", "cee'd", "ceed sw", "proceed", "xceed"]),
      m("sportage", "Sportage", ["sportage"], "suv"),
      m("rio", "Rio", ["rio"], "hatchback"),
      m("picanto", "Picanto", ["picanto"], "hatchback"),
      m("sorento", "Sorento", ["sorento"], "suv"),
      m("stonic", "Stonic", ["stonic"], "suv"),
      m("venga", "Venga", ["venga"], "mpv"),
      m("niro", "Niro", ["niro"], "suv"),
      m("ev6", "EV6", ["ev6"], "suv"),
      m("optima", "Optima", ["optima"], "sedan"),
      m("carens", "Carens", ["carens"], "mpv"),
    ],
  },
  {
    slug: "toyota",
    name: "Toyota",
    aliases: ["toyota"],
    models: [
      m("corolla", "Corolla", ["corolla", "auris"]),
      m("yaris", "Yaris", ["yaris", "yaris cross"], "hatchback"),
      m("rav4", "RAV4", ["rav4", "rav 4", "rav-4"], "suv"),
      m("avensis", "Avensis", ["avensis"]),
      m("c-hr", "C-HR", ["c-hr", "chr"], "suv"),
      m("aygo", "Aygo", ["aygo"], "hatchback"),
      m("land-cruiser", "Land Cruiser", ["land cruiser", "landcruiser"], "suv"),
      m("hilux", "Hilux", ["hilux"], "pickup"),
      m("prius", "Prius", ["prius"]),
      m("proace", "Proace", ["proace"], "van"),
      m("verso", "Verso", ["verso"], "mpv"),
    ],
  },
  {
    slug: "seat",
    name: "Seat",
    aliases: ["seat"],
    models: [
      m("leon", "Leon", ["leon"]),
      m("ibiza", "Ibiza", ["ibiza"], "hatchback"),
      m("ateca", "Ateca", ["ateca"], "suv"),
      m("arona", "Arona", ["arona"], "suv"),
      m("alhambra", "Alhambra", ["alhambra"], "mpv"),
      m("tarraco", "Tarraco", ["tarraco"], "suv"),
      m("altea", "Altea", ["altea"], "mpv"),
      m("toledo", "Toledo", ["toledo"]),
      m("cordoba", "Córdoba", ["cordoba"], "sedan"),
      m("mii", "Mii", ["mii"], "hatchback"),
    ],
  },
  {
    slug: "cupra",
    name: "Cupra",
    aliases: ["cupra"],
    models: [
      m("formentor", "Formentor", ["formentor"], "suv"),
      m("born", "Born", ["born"], "hatchback"),
      m("leon", "Leon", ["leon"]),
      m("ateca", "Ateca", ["ateca"], "suv"),
    ],
  },
  {
    slug: "volvo",
    name: "Volvo",
    aliases: ["volvo"],
    models: [
      m("xc90", "XC90", ["xc90", "xc 90"], "suv"),
      m("xc60", "XC60", ["xc60", "xc 60"], "suv"),
      m("xc40", "XC40", ["xc40", "xc 40"], "suv"),
      m("v40", "V40", ["v40"], "hatchback"),
      m("v50", "V50", ["v50"], "combi"),
      m("v60", "V60", ["v60"], "combi"),
      m("v70", "V70", ["v70", "xc70"], "combi"),
      m("v90", "V90", ["v90"], "combi"),
      m("s60", "S60", ["s60"], "sedan"),
      m("s80", "S80", ["s80"], "sedan"),
      m("s90", "S90", ["s90"], "sedan"),
    ],
  },
  {
    slug: "mazda",
    name: "Mazda",
    aliases: ["mazda"],
    models: [
      m("3", "3", ["mazda 3", "mazda3"]),
      m("6", "6", ["mazda 6", "mazda6"]),
      m("2", "2", ["mazda 2", "mazda2"], "hatchback"),
      m("cx-3", "CX-3", ["cx-3", "cx3"], "suv"),
      m("cx-30", "CX-30", ["cx-30", "cx30"], "suv"),
      m("cx-5", "CX-5", ["cx-5", "cx5"], "suv"),
      m("cx-60", "CX-60", ["cx-60", "cx60"], "suv"),
      m("mx-5", "MX-5", ["mx-5", "mx5", "miata"], "cabrio"),
      m("5", "5", ["mazda 5", "mazda5"], "mpv"),
    ],
  },
  {
    slug: "nissan",
    name: "Nissan",
    aliases: ["nissan", "nisan"],
    models: [
      m("qashqai", "Qashqai", ["qashqai", "qasqai", "kaskai"], "suv"),
      m("x-trail", "X-Trail", ["x-trail", "xtrail", "x trail"], "suv"),
      m("juke", "Juke", ["juke"], "suv"),
      m("micra", "Micra", ["micra"], "hatchback"),
      m("note", "Note", ["note"], "mpv"),
      m("leaf", "Leaf", ["leaf"], "hatchback"),
      m("navara", "Navara", ["navara"], "pickup"),
      m("almera", "Almera", ["almera"]),
      m("primera", "Primera", ["primera"]),
    ],
  },
  {
    slug: "honda",
    name: "Honda",
    aliases: ["honda"],
    models: [
      m("civic", "Civic", ["civic"]),
      m("cr-v", "CR-V", ["cr-v", "crv"], "suv"),
      m("hr-v", "HR-V", ["hr-v", "hrv"], "suv"),
      m("jazz", "Jazz", ["jazz"], "hatchback"),
      m("accord", "Accord", ["accord"]),
    ],
  },
  {
    slug: "fiat",
    name: "Fiat",
    aliases: ["fiat"],
    models: [
      m("500", "500", ["500", "500x", "500l"], "hatchback"),
      m("punto", "Punto", ["punto", "grande punto"], "hatchback"),
      m("panda", "Panda", ["panda"], "hatchback"),
      m("tipo", "Tipo", ["tipo"]),
      m("doblo", "Doblò", ["doblo"], "van"),
      m("ducato", "Ducato", ["ducato"], "van"),
      m("bravo", "Bravo", ["bravo"]),
      m("stilo", "Stilo", ["stilo"]),
      m("freemont", "Freemont", ["freemont"], "suv"),
    ],
  },
  {
    slug: "suzuki",
    name: "Suzuki",
    aliases: ["suzuki"],
    models: [
      m("vitara", "Vitara", ["vitara", "grand vitara"], "suv"),
      m("swift", "Swift", ["swift"], "hatchback"),
      m("sx4", "SX4", ["sx4", "s-cross", "sx4 s-cross"], "suv"),
      m("ignis", "Ignis", ["ignis"], "hatchback"),
      m("jimny", "Jimny", ["jimny"], "suv"),
      m("baleno", "Baleno", ["baleno"]),
      m("splash", "Splash", ["splash"], "hatchback"),
      m("wagon-r", "Wagon R", ["wagon r", "wagon r+"], "hatchback"),
    ],
  },
  {
    slug: "mitsubishi",
    name: "Mitsubishi",
    aliases: ["mitsubishi", "mitsubisi"],
    models: [
      m("outlander", "Outlander", ["outlander"], "suv"),
      m("asx", "ASX", ["asx"], "suv"),
      m("lancer", "Lancer", ["lancer"]),
      m("pajero", "Pajero", ["pajero"], "suv"),
      m("l200", "L200", ["l200", "l 200"], "pickup"),
      m("colt", "Colt", ["colt"], "hatchback"),
      m("space-star", "Space Star", ["space star"], "hatchback"),
    ],
  },
  {
    slug: "land-rover",
    name: "Land Rover",
    aliases: ["land rover", "landrover", "range rover"],
    models: [
      m("range-rover-sport", "Range Rover Sport", ["range rover sport", "rr sport"], "suv"),
      m("range-rover-evoque", "Range Rover Evoque", ["evoque"], "suv"),
      m("range-rover-velar", "Range Rover Velar", ["velar"], "suv"),
      m("discovery", "Discovery", ["discovery"], "suv"),
      m("freelander", "Freelander", ["freelander"], "suv"),
      m("defender", "Defender", ["defender"], "suv"),
      m("range-rover", "Range Rover", ["range rover", "vogue"], "suv"),
    ],
  },
  {
    slug: "jeep",
    name: "Jeep",
    aliases: ["jeep"],
    models: [
      m("grand-cherokee", "Grand Cherokee", ["grand cherokee"], "suv"),
      m("cherokee", "Cherokee", ["cherokee"], "suv"),
      m("wrangler", "Wrangler", ["wrangler"], "suv"),
      m("compass", "Compass", ["compass"], "suv"),
      m("renegade", "Renegade", ["renegade"], "suv"),
    ],
  },
  {
    slug: "tesla",
    name: "Tesla",
    aliases: ["tesla"],
    models: [
      m("model-3", "Model 3", ["model 3", "model3"], "sedan"),
      m("model-y", "Model Y", ["model y", "modely"], "suv"),
      m("model-s", "Model S", ["model s"], "sedan"),
      m("model-x", "Model X", ["model x"], "suv"),
    ],
  },
  {
    slug: "porsche",
    name: "Porsche",
    aliases: ["porsche", "porse"],
    models: [
      m("cayenne", "Cayenne", ["cayenne"], "suv"),
      m("macan", "Macan", ["macan"], "suv"),
      m("911", "911", ["911", "carrera"], "coupe"),
      m("panamera", "Panamera", ["panamera"]),
      m("taycan", "Taycan", ["taycan"]),
      m("boxster", "Boxster/Cayman", ["boxster", "cayman"], "coupe"),
    ],
  },
  {
    slug: "alfa-romeo",
    name: "Alfa Romeo",
    aliases: ["alfa romeo", "alfa"],
    models: [
      m("giulia", "Giulia", ["giulia"], "sedan"),
      m("giulietta", "Giulietta", ["giulietta"], "hatchback"),
      m("stelvio", "Stelvio", ["stelvio"], "suv"),
      m("159", "159", ["159"]),
      m("147", "147", ["147"], "hatchback"),
      m("156", "156", ["156"]),
      m("mito", "MiTo", ["mito"], "hatchback"),
    ],
  },
  {
    slug: "chevrolet",
    name: "Chevrolet",
    aliases: ["chevrolet", "chevy"],
    models: [
      m("cruze", "Cruze", ["cruze"]),
      m("spark", "Spark", ["spark"], "hatchback"),
      m("aveo", "Aveo", ["aveo"], "hatchback"),
      m("captiva", "Captiva", ["captiva"], "suv"),
      m("lacetti", "Lacetti", ["lacetti", "nubira"]),
      m("camaro", "Camaro", ["camaro"], "coupe"),
    ],
  },
  { slug: "mini", name: "Mini", aliases: ["mini cooper", "mini"], models: [m("cooper", "Cooper", ["cooper", "one", "clubman"], "hatchback"), m("countryman", "Countryman", ["countryman"], "suv")] },
  { slug: "smart", name: "Smart", aliases: ["smart"], models: [m("fortwo", "ForTwo", ["fortwo", "for two"], "hatchback"), m("forfour", "ForFour", ["forfour", "for four"], "hatchback")] },
  { slug: "subaru", name: "Subaru", aliases: ["subaru"], models: [m("forester", "Forester", ["forester"], "suv"), m("outback", "Outback", ["outback"], "combi"), m("impreza", "Impreza", ["impreza"]), m("xv", "XV", ["xv"], "suv"), m("legacy", "Legacy", ["legacy"])] },
  { slug: "lexus", name: "Lexus", aliases: ["lexus"], models: [m("rx", "RX", ["rx", "rx450h", "rx 450h"], "suv"), m("nx", "NX", ["nx"], "suv"), m("is", "IS", ["is"], "sedan"), m("ux", "UX", ["ux"], "suv")] },
  { slug: "jaguar", name: "Jaguar", aliases: ["jaguar"], models: [m("xf", "XF", ["xf"], "sedan"), m("xe", "XE", ["xe"], "sedan"), m("f-pace", "F-Pace", ["f-pace", "fpace"], "suv"), m("xj", "XJ", ["xj"], "sedan")] },
  { slug: "mg", name: "MG", aliases: ["mg"], models: [m("zs", "ZS", ["zs"], "suv"), m("hs", "HS", ["hs"], "suv"), m("mg4", "MG4", ["mg4", "mg 4"], "hatchback")] },
  { slug: "dodge", name: "Dodge", aliases: ["dodge"], models: [m("ram", "RAM", ["ram"], "pickup"), m("challenger", "Challenger", ["challenger"], "coupe"), m("journey", "Journey", ["journey"], "suv")] },
  { slug: "chrysler", name: "Chrysler", aliases: ["chrysler"], models: [m("voyager", "Voyager", ["voyager", "grand voyager"], "mpv"), m("300c", "300C", ["300c", "300 c"], "sedan")] },
  { slug: "lada", name: "Lada", aliases: ["lada", "vaz"], models: [m("niva", "Niva", ["niva", "4x4"], "suv"), m("samara", "Samara", ["samara"])] },
  { slug: "ssangyong", name: "SsangYong", aliases: ["ssangyong", "ssang yong"], models: [m("korando", "Korando", ["korando"], "suv"), m("rexton", "Rexton", ["rexton"], "suv"), m("tivoli", "Tivoli", ["tivoli"], "suv")] },
  { slug: "isuzu", name: "Isuzu", aliases: ["isuzu"], models: [m("d-max", "D-Max", ["d-max", "dmax"], "pickup")] },
  { slug: "iveco", name: "Iveco", aliases: ["iveco"], models: [m("daily", "Daily", ["daily"], "van")] },
  { slug: "byd", name: "BYD", aliases: ["byd"], models: [m("atto-3", "Atto 3", ["atto 3", "atto3"], "suv"), m("seal", "Seal", ["seal"], "sedan"), m("dolphin", "Dolphin", ["dolphin"], "hatchback")] },
  { slug: "trabant", name: "Trabant", aliases: ["trabant", "trabi"], models: [m("601", "601", ["601"])] },
];

export const MAKE_BY_SLUG = new Map(CATALOG.map((mk) => [mk.slug, mk]));

export function makeName(slug: string | null | undefined): string | null {
  if (!slug) return null;
  return MAKE_BY_SLUG.get(slug)?.name ?? slug;
}

export function modelName(makeSlug: string | null | undefined, modelSlug: string | null | undefined): string | null {
  if (!makeSlug || !modelSlug) return null;
  return MAKE_BY_SLUG.get(makeSlug)?.models.find((md) => md.slug === modelSlug)?.name ?? modelSlug;
}
